name: daily_wash
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences:
  http:
  provider:
  auto_size_text:
  intl:
  font_awesome_flutter:
  carousel_slider:
  flutter_xlider:
  google_maps_flutter: ^0.5.21+7
  location:
  flutter_google_places: 0.2.3
  webview_flutter:
  google_maps_webservice:
  geocoder:
  geolocator:
  flutter_launcher_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/logodailywash.jpeg"

flutter:

  uses-material-design: true
  assets:
    - res/fonts/
    - res/graphics/
    - res/icons/

  fonts:
    - family: SFProBold
      fonts:
        - asset: res/fonts/sfprobold.otf

    - family: SFPro
      fonts:
        - asset: res/fonts/sfpro.otf


